"""initial schema with indexes and booking constraint

Revision ID: 3acc282e0e25
Revises: 
Create Date: 2026-06-03 16:39:41.896502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acc282e0e25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointments_calendar_event_id', ['calendar_event_id'], unique=False)
        batch_op.create_index('ix_appointments_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_appointments_patient_id', ['patient_id'], unique=False)
        batch_op.create_index('ix_appointments_scheduled_at', ['scheduled_at'], unique=False)
        batch_op.create_index('ix_appointments_status', ['status'], unique=False)
        batch_op.create_unique_constraint('uq_appointments_scheduled_at_active', ['scheduled_at'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patients_last_contact', ['last_contact'], unique=False)
        batch_op.create_index('ix_patients_phone', ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('ix_patients_phone')
        batch_op.drop_index('ix_patients_last_contact')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_appointments_scheduled_at_active', type_='unique')
        batch_op.drop_index('ix_appointments_status')
        batch_op.drop_index('ix_appointments_scheduled_at')
        batch_op.drop_index('ix_appointments_patient_id')
        batch_op.drop_index('ix_appointments_created_at')
        batch_op.drop_index('ix_appointments_calendar_event_id')

    # ### end Alembic commands ###
